TODO Section (see ~/devel/conventional-commits/TODO for details)
- [x] feat: add warning if sourced files are missing (feat-warning)
- [x] feat: add upgrade repos function (feat-upgrade-repos)
- [x] refactor: refactor options (refactor-options)
- [x] refactor: remove runtime (refactor-runtime)
- [x] refactor: remove __find_trailing_whitespace__ (refactor-remove-ws)
- [x] refactor: remove __find_trailing_whitespace_l__ (refactor-remove-ws)
- [ ] refactor: rewrite git search (refactor-git-search)
      * Ignore backup gits and .cache
- [ ] refactor: replace _dirfile tempfile with array (refactor-array)
- [ ] feat: add __chooser__ (feat-chooser)
- [ ] feat: add timestamp option (feat-timestamp)
- [ ] perf: [flesh this out: use coproc?] (perf-update-repos)
- [ ] refactor: rewrite options using getopt (refactor-options-getopt)
